### ISSUE TITLE
Cannot create account using SSO

### ISSUE THREAD

**Issue by jannavarro** [exceptionless/Exceptionless#171]
In login page I used Github and Google as SSO but both give an error.

![image](https://cloud.githubusercontent.com/assets/4499051/12051793/1e8e1582-af43-11e5-9ea1-0d002fa4866d.png)

**Comment by niemyjski** [comment]
Thanks for reporting this. I've just committed some additional logging for this: https://github.com/exceptionless/Exceptionless/commit/3e9373180974777fef267a4396b9517098990955 can you please try again so I can take a look at the actual error you are getting.

**Comment by niemyjski** [comment]
@jannavarro Are you still getting the same error?

**Comment by jannavarro** [comment]
@niemyjski sorry for the late reply. I am in a different time zone. I am still getting the error for facebook, google and github. I did not try Microsoft. UTC time right now is 12/31/2015 4:28am.

**Comment by niemyjski** [comment]
Thanks for the heads up I'll look though our logs. For now can you try signing in with a user name and password and then link it to your external login

**Comment by niemyjski** [comment]
I've deployed a fix for this issue. You should now be able to register without issue.

**Comment by jannavarro** [comment]
@niemyjski thanks! I started contributing small changes in OpenLiveWriter recently. I hope I can contribute here too.
