### ISSUE TITLE
I have some problems with the docker compose deployment.

### ISSUE THREAD

**Issue by quan01994** [exceptionless/Exceptionless#428]
````
version: '3.4'

services:
  api:
    depends_on:
      - elasticsearch
      - redis
    build:
      context: .
      target: api
    image: exceptionless/api-ci:latest
    environment:
      EX_AppMode: Production
      EX_ConnectionStrings__Cache: provider=redis
      EX_ConnectionStrings__Elasticsearch: server=http://elasticsearch:9200
      #EX_ConnectionStrings__Email: smtps://user:password@smtp.host.com:587
      EX_ConnectionStrings__MessageBus: provider=redis
      #EX_ConnectionStrings__Metrics: provider=statsd;server=statsd;
      EX_ConnectionStrings__Queue: provider=redis
      EX_ConnectionStrings__Redis: server=redis,abortConnect=false
      EX_ConnectionStrings__Storage: provider=folder;path=/app/storage
      EX_RunJobsInProcess: 'false'
    ports:
      - 5050:80
    volumes:
      - C:/docker/volume/exceptionless/appdata:/app/storage

  jobs:
    depends_on:
      - api
    build:
      context: .
      target: job
    image: exceptionless/job-ci:latest
    command: run-all
    environment:
      EX_AppMode: Production
      EX_ConnectionStrings__Cache: provider=redis
      EX_ConnectionStrings__Elasticsearch: server=http://elasticsearch:9200
      #EX_ConnectionStrings__Email: smtps://user:password@smtp.host.com:587
      EX_ConnectionStrings__MessageBus: provider=redis
      #EX_ConnectionStrings__Metrics: provider=statsd;server=statsd;
      EX_ConnectionStrings__Queue: provider=redis
      EX_ConnectionStrings__Redis: server=redis,abortConnect=false
      EX_ConnectionStrings__Storage: provider=folder;path=/app/storage
    volumes:
      - C:/docker/volume/exceptionless/appdata:/app/storage

  ui:
    image: exceptionless/ui-ci:latest
    environment:
      AppMode: Development
      EX_ApiUrl: http://localhost:5050
    ports:
      - 5100:80

  elasticsearch:
    image: exceptionless/elasticsearch:1
    environment:
      cluster.name: 'exceptionless'
      bootstrap.memory_lock: 'true'
      discovery.type: single-node
      ES_JAVA_OPTS: '-Xms512m -Xmx512m'
      xpack.security.enabled: 'false'
      xpack.graph.enabled: 'false'
      xpack.watcher.enabled: 'false'
    ports:
      - 9200:9200
      - 9300:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - C:/docker/volume/exceptionless/esdata:/usr/share/elasticsearch/data

  # kibana:
  #   depends_on:
  #     - elasticsearch
  #   image: exceptionless/kibana:1
  #   environment:
  #     xpack.security.enabled: 'false'
  #   ports:
  #     - 5601:5601

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
````

api have some problems when i search infomation

[08:31:14 ERR] Error getting mapping for index events
Server Error (Index=events Type=index_not_found_exception): no such index
[404] GET /events/_mapping/events

[08:31:14 ERR] Error getting mapping for index events
Server Error (Index=events Type=index_not_found_exception): no such index
[404] GET /events/_mapping/events
![image](https://user-images.githubusercontent.com/20533465/59666787-1d358e00-91e8-11e9-9d16-a7817a978025.png)

this is es log
![image](https://user-images.githubusercontent.com/20533465/59666873-4a823c00-91e8-11e9-8e42-bca3373aeb0a.png)

**Comment by niemyjski** [comment]
Can you hit Elasticsearch on port 9200? I'd make sure that's exposed and you can hit it.

**Comment by quan01994** [comment]
![image](https://user-images.githubusercontent.com/20533465/59892783-23588400-940d-11e9-87c8-5a3d2fa1a036.png)
Visible in the browser

**Comment by niemyjski** [comment]
If you run `GET _cat/indicies` in elastic search is there any indices. It's like it cannot talk to it. That docker compose file won't even run on my machine. Have you just tried using ours as is? Can you do `docker-compose up elasticsearch redis` and then clone this repository and copy some of the config to the yaml file in the web project and start debugging? It might say a different error (I'm really curious what the error is).

**Comment by quan01994** [comment]
![image](https://user-images.githubusercontent.com/20533465/59999346-55c7e280-9694-11e9-84c9-c8f2b5132a51.png)

400 bad request

**Comment by niemyjski** [comment]
Here is the link to documentation: https://www.elastic.co/guide/en/elasticsearch/reference/5.6/cat-indices.html

**Comment by napoleonjang** [comment]
> Here is the link to documentation: https://www.elastic.co/guide/en/elasticsearch/reference/5.6/cat-indices.html

I encountered the same problem, however, the elasticsearch _cat/indices command runs successfully:
![image](https://user-images.githubusercontent.com/2639201/60424028-05b3c780-9c22-11e9-9c05-105c8464456e.png)

It seams like  index "events“ not built in  elasticsearch  ?

**Comment by quan01994** [comment]
````
version: '3.4'

services:
  api:
    depends_on:
      - elasticsearch
      - redis
    image: exceptionless/api-ci:latest
    container_name: ex_api
    environment:
      EX_AppMode: Production
      EX_ConnectionStrings__Cache: provider=redis
      EX_ConnectionStrings__Elasticsearch: server=http://elasticsearch:9200
      #EX_ConnectionStrings__Email: smtps://user:password@smtp.host.com:587
      EX_ConnectionStrings__MessageBus: provider=redis
      #EX_ConnectionStrings__Metrics: provider=statsd;server=statsd;
      EX_ConnectionStrings__Queue: provider=redis
      EX_ConnectionStrings__Redis: server=redis,abortConnect=false
      EX_ConnectionStrings__Storage: provider=folder;path=/app/storage
      EX_RunJobsInProcess: 'false'
    ports:
      - 5000:80
    volumes:
      - C:/docker/volume/exceptionless/appdata:/app/storage

  jobs:
    depends_on:
      - api
    image: exceptionless/job-ci:latest
    container_name: ex_job
    command: run-all
    environment:
      EX_AppMode: Production
      EX_ConnectionStrings__Cache: provider=redis
      EX_ConnectionStrings__Elasticsearch: server=http://elasticsearch:9200
      #EX_ConnectionStrings__Email: smtps://user:password@smtp.host.com:587
      EX_ConnectionStrings__MessageBus: provider=redis
      #EX_ConnectionStrings__Metrics: provider=statsd;server=statsd;
      EX_ConnectionStrings__Queue: provider=redis
      EX_ConnectionStrings__Redis: server=redis,abortConnect=false
      EX_ConnectionStrings__Storage: provider=folder;path=/app/storage
    volumes:
      - C:/docker/volume/exceptionless/appdata:/app/storage

  ui:
    image: exceptionless/ui-ci:latest
    container_name: ex_ui
    environment:
      AppMode: Development
      BaseUrl: http://localhost:5000
      EX_ApiUrl: http://localhost:5000
    ports:
      - 5100:80

  elasticsearch:
    container_name: ex_es
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.16
    environment:
      cluster.name: 'exceptionless'
      bootstrap.memory_lock: 'true'
      discovery.type: single-node
      ES_JAVA_OPTS: '-Xms512m -Xmx512m'
      xpack.security.enabled: 'false'
      xpack.graph.enabled: 'false'
      xpack.watcher.enabled: 'false'
    ports:
      - 9200:9200
      - 9300:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - C:/docker/volume/exceptionless/esdata:/usr/share/elasticsearch/data

  # kibana:
  #   depends_on:
  #     - elasticsearch
  #   image: exceptionless/kibana:1
  #   environment:
  #     xpack.security.enabled: 'false'
  #   ports:
  #     - 5601:5601

  redis:
    container_name: ex_redis
    image: redis:alpine
    ports:
      - 6379:6379
````
Still have problems
![image](https://user-images.githubusercontent.com/20533465/60644820-c4155d80-9e69-11e9-8bb9-1bfd612b307e.png)

![image](https://user-images.githubusercontent.com/20533465/60644853-d5f70080-9e69-11e9-89a7-30caaa96fa25.png)

**Comment by niemyjski** [comment]
Were you able to resolve this issue?

**Comment by napoleonjang** [comment]
> Were you able to resolve this issue?

not yet   :<

**Comment by quan01994** [comment]
> 你能解决这个问题吗？

I don't need to deploy it with docker.

**Comment by niemyjski** [comment]
I'm looking into this now with docker-compose. Can you clone our repository and use the latest docker compose file (I fixed a bunch of issues as well as added configuration settings that can be modified to set api/base url). Also I'd recommend opening up [kibana](http://localhost:5601/app/kibana#/dev_tools/console) and running `delete *` and restart all the docker containers to start over just to be safe. Please note running the previous command will remove all elasticsearch data, so only do that if you have nothing else inside of elastic. Can you let me know how if you are still running into errors.

**Comment by napoleonjang** [comment]
still no work after following your instructions:
1.pull the latest repo
2.run cmd:docker-compose up
3. delete * in kibana
4.restart containers
5. the same error still happens 

api log:
![image](https://user-images.githubusercontent.com/2639201/62048189-d69f6e80-b23e-11e9-91e8-453194925d3f.png)

client log:
![image](https://user-images.githubusercontent.com/2639201/62048204-e0c16d00-b23e-11e9-9f01-d15c0c8973e5.png)

ps: I found that the container 'job' will automatically shut down:
![image](https://user-images.githubusercontent.com/2639201/62048364-4ada1200-b23f-11e9-9133-60b33e90f9d3.png)

thx!

**Comment by napoleonjang** [comment]
> still no work after following your instructions:
> 1.pull the latest repo
> 2.run cmd:docker-compose up
> 3. delete * in kibana
> 4.restart containers
> 5. the same error still happens
> 
> api log:
> ![image](https://user-images.githubusercontent.com/2639201/62048189-d69f6e80-b23e-11e9-91e8-453194925d3f.png)
> 
> client log:
> ![image](https://user-images.githubusercontent.com/2639201/62048204-e0c16d00-b23e-11e9-9f01-d15c0c8973e5.png)
> 
> ps: I found that the container 'job' will automatically shut down:
> ![image](https://user-images.githubusercontent.com/2639201/62048364-4ada1200-b23f-11e9-9133-60b33e90f9d3.png)
> 
> thx!

delete * in kibana:
![image](https://user-images.githubusercontent.com/2639201/62048474-9391cb00-b23f-11e9-9faa-211dc1ece3a5.png)

**Comment by niemyjski** [comment]
Are you using the exact docker-compose file we ship with?

**Comment by napoleonjang** [comment]
it works now!  I can see the exceptions in dashboard.   However, after modify the ui and api url from localtest.me to an internet IP, the login api call failed with 403 http code: 
![image](https://user-images.githubusercontent.com/2639201/63210922-0e555400-c123-11e9-99b6-c5ead6205e31.png)

![image](https://user-images.githubusercontent.com/2639201/63210926-190fe900-c123-11e9-8479-cea6a66e8c79.png)

**Comment by napoleonjang** [comment]
> Are you using the exact docker-compose file we ship with?

It works now! I can see the exceptions in dashboard.  Thanks! :)
However, after modify the ui and api url from localtest.me to  address  in the internal network, the login api call failed with 403 http code:
![image](https://user-images.githubusercontent.com/2639201/63211013-2c6f8400-c124-11e9-8d39-46730e394a1c.png)


docker-compose file:
![image](https://user-images.githubusercontent.com/2639201/63211027-680a4e00-c124-11e9-94ff-75a54a771074.png)
![image](https://user-images.githubusercontent.com/2639201/63211029-7ce6e180-c124-11e9-9fb5-69a651550c6f.png)

![image](https://user-images.githubusercontent.com/2639201/63211036-853f1c80-c124-11e9-8354-2251790ee940.png)

**Comment by niemyjski** [comment]
All that looks correct, what happens when you hit `http://192.168.0.13:5000/api/v2/about`?

**Comment by napoleonjang** [comment]
> All that looks correct, what happens when you hit `http://192.168.0.13:5000/api/v2/about`?

auto redirect to https://192.168.0.13/api/v2/about  
and the result is : ERR_CONNECTION_REFUSED

**Comment by niemyjski** [comment]
Can you even ping that IP address? That's an internal address and I doubt it will work out of the network it's hosted on? Are you on the same network? You should check out the updated docker wiki. We added an ssl section which gives you free ssl and does ssl termination as well you can easily host exceptionless behind a domain name :)

**Comment by napoleonjang** [comment]
> Can you even ping that IP address? That's an internal address and I doubt it will work out of the network it's hosted on? Are you on the same network? You should check out the updated docker wiki. We added an ssl section which gives you free ssl and does ssl termination as well you can easily host exceptionless behind a domain name :)

yes,  command "telnet  192.168.0.13 5000 ”   works fine!
all the snapshot images above are  in the same host server with IP "192.168.0.13" 

when login,  API log  is (notice the last log):
![image](https://user-images.githubusercontent.com/2639201/63211765-3e562480-c12e-11e9-805d-c4eddbdce5a1.png)

**Comment by napoleonjang** [comment]
> Can you even ping that IP address? That's an internal address and I doubt it will work out of the network it's hosted on? Are you on the same network? You should check out the updated docker wiki. We added an ssl section which gives you free ssl and does ssl termination as well you can easily host exceptionless behind a domain name :)

Here is a work around solution,    add 
192.168.0.13  ex-ui.localtest.me    
192.168.0.13  ex-api.localtest.me    
in hosts  file 
:)
Now, everything works fine finally ~:)  
thanks!

**Comment by napoleonjang** [comment]
> Can you even ping that IP address? That's an internal address and I doubt it will work out of the network it's hosted on? Are you on the same network? You should check out the updated docker wiki. We added an ssl section which gives you free ssl and does ssl termination as well you can easily host exceptionless behind a domain name :)

hi, email verification not works.  :(
I can  receive a validation email,  from the mail, click "Verify Address", enter the website without error. However, still did not verify the state of the mailbox.

**Comment by niemyjski** [comment]
Can you look in your browser and see what the end point it called? You may need to try again as every time you click verify it creates a new token and invalidates the last.

**Comment by ejsmith** [comment]
This is an HSTS thing. You need follow the instructions here: https://really-simple-ssl.com/knowledge-base/clear-hsts-browser/

**Comment by napoleonjang** [comment]
> Can you look in your browser and see what the end point it called? You may need to try again as every time you click verify it creates a new token and invalidates the last.

hi, I repeated procedure again:
![image](https://user-images.githubusercontent.com/2639201/63222493-4750ff80-c1db-11e9-989c-d38501fca630.png)

click "verify":
the url is http://ex-ui.localtest.me:5100/account/verify?token=/RPcSOYWSWtFiT3CaP206hKzCbc4P6ZC7sQfKHp0t#!/type/error/dashboard

![image](https://user-images.githubusercontent.com/2639201/63222495-589a0c00-c1db-11e9-9cde-6e6a86b08ea9.png)

**Comment by napoleonjang** [comment]
> This is an HSTS thing. You need follow the instructions here: https://really-simple-ssl.com/knowledge-base/clear-hsts-browser/

thanks! I will try it. :)
