### ISSUE TITLE
Verify email for the first account in a clean installation does not apply correctly

### ISSUE THREAD

**Issue by brentljohnson** [exceptionless/Exceptionless#72]
The "Verify Address" button opens a new browser tab on the user however the user continues to appear as "Email not verified...".  Checking the database the user entry has been correctly updated.  The UI eventually updates to indicate the user is verified, presumably after a cached object has expired.
![capture1a](https://cloud.githubusercontent.com/assets/11605239/6835060/1613ace6-d39d-11e4-9322-ad0265de203f.JPG)
![capture1b](https://cloud.githubusercontent.com/assets/11605239/6835062/1b7aaaae-d39d-11e4-9646-f7baf9c1cba4.JPG)

**Comment by brentljohnson** [comment]
PS:
Testing with API running in debug under VS and UI running with "grunt serve".
web.config changed to "WebsiteMode" = "Production" and updated email addresses.

**Comment by niemyjski** [comment]
What does the request look like in the browser? Does it show that it's been updated? Is it even doing a request to get the user after you click verified?

**Comment by brentljohnson** [comment]
The first image above is the new browser window opened by clicking "Verify Address", showing the user as unchanged.  The page loads from scratch so it's definitely hitting the API:
http://localhost:50000/api/v2/users/me  
Response body
{
  "has_local_account": true,
  "id": "551330be0a4c7b0708a04eec",
  "full_name": "Brent Johnson",
  "email_address": "xxxxx@xxxxx",
  "email_notifications_enabled": true,
  "is_email_address_verified": false,
  "is_active": true,
  "is_invite": false,
  "roles": [
    "client",
    "user",
    "global"
  ]
}
MongoDB entry for user (as indicated in second image above) shows database update has applied.

**Comment by brentljohnson** [comment]
PS:  The JSON above is from a more recent test run so the user Id does not match the original images.

**Comment by niemyjski** [comment]
It's all good. I'll take a look and see what's causing this.

**Comment by niemyjski** [comment]
I tracked this down! It only happens on page load. It happens because we delay load signalr which hasn't loaded and thus doesn't get the push notification.

**Comment by niemyjski** [comment]
This has been fixed in the latest ui build. Can you please pull it down and verify.

**Comment by brentljohnson** [comment]
I now see the blue popup indicating my account has been email verified, but I'm still seeing my account as "email not verified" in the account/manage page.  No change following a logout/login. Resend verify is ignored - understandable with the API having seen the update go through.  
Before the test I delete the MongoDB and wipe the Redis (delete dump file & cycle the service). Is there anything else I should be clearing to reset to a clean development environment?  ElasticSearch in the frame somehow?

**Comment by niemyjski** [comment]
No, you shouldn't need to reset anything. Refreshing the browser is all that is needed.

**Comment by niemyjski** [comment]
Is there any chance we could meet up and take a look into this together? I'm not seeing it after my latest commit.

**Comment by brentljohnson** [comment]
Not with me running inside our corporate firewall.  I've debugged the verify email address process and can see it invalidating the cache.  When you verify and the new tab/window pops up on the account/manage page (just before the blue box appears) do you see the account as still waiting verification?  I do, but now (as opposed to yesterday) I can F5 and see the account update. Is the API generating a SignalR event for the update to the user that should refresh the account/manage page?  My best guess is a race condition where the user is being updated back to email unvalidated in the cache after the update to validated occurs.

**Comment by niemyjski** [comment]
Yes, the API generates a SignalR message any time an entity is changed and we subscribe to all of those. I need to deploy this fix to production still.

It's hard to say without stepping into this. The controller action for verifying and creating the validation token is extremely simple. I didn't see anything that would be causing this issue, we are never caching the user server side (at least in the [controller](https://github.com/exceptionless/Exceptionless/blob/master/Source/Api/Controllers/UserController.cs)): 

Would you be free after work to take a look into this with me? I'd be more than happy to drive.

**Comment by niemyjski** [comment]
I've deployed the fix to our live website so users should be less likely to see this (I still haven't been able to reproduce what you are seeing). Would it be possible to record a screencast (maybe with jing) with what you are seeing using the latest builds?

**Comment by niemyjski** [comment]
Are you still seeing this issue?

**Comment by brentljohnson** [comment]
Yes.  Got the latest updates this morning and still experiencing the same issue.  Tried switching to "Dev" mode but verify email address emails are not produced (confirmed the "AllowedOutboundAddresses" is correctly set).  Tried disabling Redis by commenting out the connection string, no improvement - but then I noticed you removed this too.  I'll try on my home PC tonight so eliminate an issue with my work machine.

**Comment by niemyjski** [comment]
Redis is disabled by default when there is an empty connection string defined. Is your mail settings set?

**Comment by brentljohnson** [comment]
I'm running Paper Cut locally.  Default email settings works fine when in Production mode.

**Comment by niemyjski** [comment]
What's papercut? If you want I could meet up with you after work and take a look into this issue with you? I'll be free for a little bit later tonight

**Comment by brentljohnson** [comment]
Paper Cut is an SMTP simulator with a local UI so I can click the verify links.  https://papercut.codeplex.com/

**Comment by Phyxion** [comment]
I also have problems with verifying the email address. 
I have this situation:
Api runs on port 888.
UI runs on port 999.

The link that gets generated in the email is the one from the Api (port 888). Opening that results in a 404 not found. Which seems logical as it's a /account url which only seems to be used by the UI. However, when I change the port to the correct one it still doesn't verify me. I can refresh what I want but it's doing absolutely nothing.

**Comment by niemyjski** [comment]
You need to set your BaseUrl to point to the UI on port 999. Then all links will be generated properly. 

```xml
<!-- Base url for the ui used to build links in emails and other places. -->
<add key="BaseURL" value="http://localhost:9001/#" />
```

Did this fix this issue?

**Comment by Phyxion** [comment]
Thanks, it works now. It seems I missed the /# at the end. Might be useful to mention this somewhere :+1:

**Comment by niemyjski** [comment]
@Phyxion @brentljohnson is it safe to close this? I've never been able to reproduce this issue. We also did a massive amount of work to get rid of mongo and just use elastic search (one less moving part and it may have fixed this for you).

**Comment by Phyxion** [comment]
Yes, it can be closed. The baseurl needed the /# at the end to work.
